generate new django project with docker
Acoowa/TaskManager pull request #1
Opened 2024-04-12 04:23 UTC by Acoowa

2024-04-15 04:14 UTC, aleksandr-semenov-dbp requested changes
Надо убрать из репозитория настроки IDE (.idea)

2024-04-16 03:56 UTC, Acoowa commented
поправил в третьем реквесте

2024-04-22 05:31 UTC, aleksandr-semenov-dbp requested changes
нужно убрать настройки IDE из репозитория

2024-04-29 04:32 UTC, aleksandr-semenov-dbp requested changes

2024-04-29 04:32 UTC, aleksandr-semenov-dbp commented on Dockerfile
> +RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.1.7
прямо очень старый poetry, надо стартовать проект с чем-то поактуальнее

2024-05-06 04:01 UTC, aleksandr-semenov-dbp approved these changes

2024-05-12 08:11 UTC, merged